// src/lib/quotes.ts

export const quotes: string[] = [
  "Un viaje de mil millas comienza con un solo paso.",
  "La disciplina es el puente entre las metas y los logros.",
  "El dolor que sientes hoy será la fuerza que sientas mañana.",
  "No tienes que ser grande para empezar, pero tienes que empezar para ser grande.",
  "La diferencia entre lo imposible y lo posible reside en la determinación de una persona.",
  "El éxito es la suma de pequeños esfuerzos repetidos día tras día.",
  "Cree en ti mismo y todo lo que eres. Reconoce que hay algo dentro de ti que es más grande que cualquier obstáculo.",
  "Cada paso cuenta, no importa cuán pequeño sea.",
  "No se trata de la perfección. Se trata del esfuerzo.",
  "Tu cuerpo puede soportar casi cualquier cosa. Es tu mente la que tienes que convencer.",
  "La motivación es lo que te pone en marcha. El hábito es lo que hace que sigas.",
  "Conviértete en la persona que quieres ser, un paso a la vez.",
  "No mires atrás, no vas por ese camino.",
  "La energía y la persistencia conquistan todas las cosas.",
  "El único mal entrenamiento es el que no se hizo.",
  "Empújate, porque nadie más lo va a hacer por ti.",
  "No esperes la oportunidad. Créala.",
  "El secreto para salir adelante es empezar.",
  "Cuida tu cuerpo. Es el único lugar que tienes para vivir.",
  "Un pequeño progreso cada día suma grandes resultados.",
  "La acción es la clave fundamental de todo éxito.",
  "No te rindas. Los grandes logros llevan tiempo.",
  "Cada día es una nueva oportunidad para cambiar tu vida.",
  "La fuerza no viene de la capacidad física. Viene de una voluntad indomable.",
  "No te detengas cuando estés cansado. Detente cuando hayas terminado.",
  "El sudor es la grasa llorando.",
  "Estás a solo un entrenamiento de un buen estado de ánimo.",
  "El movimiento es un medicamento para crear el cambio en el estado físico, emocional y mental de una persona.",
  "Hazlo por el 'después de' la sensación.",
  "Cuando sientas que vas a rendirte, piensa por qué empezaste."
];
